engines:
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**
  - spec/**

exclude_paths:
- "src/loggers-bugfix.ts"
